# Estructuras de Datos y Control de Flujo
En este cuaderno de Jupyter se cubren las estructuras de datos básicos del lenguaje como:
1. Dictionaries
2. Tuples 
3. Arrays 

Una nota importante sobre el acceso por índices en Julia es que los __índices no inician en el elemento 0__ como en otros lenguajes, el __primer elemento comienza en el índice 1.__

Dichas estructuras de datos son muy importante dado las limitaciones de hacer variables de un solo dato. Por otro lado, se cubre la parte de control de flujo la cual incluye: 
- While loop
- For loop
- If else 
- Funciones en Julia

## Dictionaries 
Un diccionario es una estructura de datos la cual contiene palabras claves asociadas a un valor, similar a un libro telefónico. En el libro telefónico la palabra clave o _key_ seria el nombre de la persona y el valor o _data_ asociado es el numero telefónico. Para crear un diccionario se hace de la siguiente forma:


In [1]:
dictionary = Dict("Jose" => 20063456, "Marco" => "23458679", "Maria" => 12345678)

Dict{String,Any} with 3 entries:
  "Marco" => "23458679"
  "Maria" => 12345678
  "Jose"  => 20063456

El ejemplo anterior crea un diccionario con 3 entradas similar a un libro telefónico, Jose y María son palabras claves cuyos valores son <code>Int</code> mientras que el valor asociado a Marco es un <code>string</code>. Los datos de un diccionario pueden ser de diferentes tipos. Para agregar un nuevo valor a un diccionario se utiliza la siguiente sintaxis.

In [2]:
dictionary["Emergencias"] = "911"

"911"

In [3]:
#Revisando el nuevo contenido del diccionario
dictionary

Dict{String,Any} with 4 entries:
  "Emergencias" => "911"
  "Marco"       => "23458679"
  "Maria"       => 12345678
  "Jose"        => 20063456

Para accesar los valores dentro de un diccionario se debe utilizar la palabra clave que se desea buscar por ejemplo:

In [4]:
dictionary["Marco"]

"23458679"

Los diccionarios no pueden ser accesados por indices como un arreglo. 

In [5]:
# Lo siguiente va a generar un error
dictionary[1]

LoadError: KeyError: key 1 not found

## Tuples
Los _Tuples_ son similar a un arreglo, su diferencia principal es el hecho que sus contenidos no pueden ser modificados, para crear un _Tuple_ se utilizan los paréntesis <code>( )</code>, por ejemplo:


In [6]:
tuple = ("Lunes", "Martes", "Miercoles", "Jueves", "Viernes")

("Lunes", "Martes", "Miercoles", "Jueves", "Viernes")

Se pueden accesar por índices como un arreglo:

In [7]:
tuple[4]

"Jueves"

In [8]:
#Si se intenta modificar los contenidos de un Tuple se va a generar un error
tuple[3] = "Domingo"

LoadError: MethodError: no method matching setindex!(::NTuple{5,String}, ::String, ::Int64)

## Arrays
Los arreglos si pueden ser modificados, contienen datos de forma ordenada que pueden ser accesados por índices y se crean utilizando paréntesis cuadrados <code>[ ]</code>. Algunos ejemplos de arreglos en Julia son:


In [9]:
array1 = [1,2,3,4,5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [10]:
array2 =["Jose","Marco","Maria","Marta"]

4-element Array{String,1}:
 "Jose"
 "Marco"
 "Maria"
 "Marta"

In [11]:
# Julia tambien soporta arreglos cuyo contenido no es de un solo tipo:
array3 = [1.5,10,45,"123","hola!"]

5-element Array{Any,1}:
  1.5
 10
 45
   "123"
   "hola!"

Para accesar un arreglo y modificar su contenido se hacen por medio de su índice:

In [12]:
println(array1[1])
array1[1] = 30
#Notese que algunos arreglos pueden contener "Any" y otros si tienen un tipo en especifico

1


30

Si se desea crear un arreglo de números aleatorios se puede utilizar la función <code>rand()</code> dentro de ella se puede indicar la cantidad de números a generar. Luego, Julia crea un arreglo con la cantidad de números deseados. Los números van entre 0 y 1.

In [13]:
arr = rand(10)

10-element Array{Float64,1}:
 0.9632410780347216
 0.4438744925706273
 0.23162764978796035
 0.46602522764525456
 0.5835843849681805
 0.009085531328106633
 0.30705530291113803
 0.21918822830439644
 0.7116787593006331
 0.10884820786886285

### Funciones útiles 
Algunas funciones útiles para el manejo de estructuras de datos, en particular arrays son:
1. <code>push!(array_or_vector_to_push, arg)</code> Agrega un valor _arg_ al final del arreglo.
2. <code>pop!(array_or_vector)</code> Retorna y elimina el ultimo valor de la lista ordenada. 
3. <code>popat!(array_or_vector_to_pop ,index)</code> Retorna y elimina el valor en algún índice, luego reajusta los contenidos del arreglo. 
4. <code>insert!(array_or_vector, index, arg)</code> Inserta un valor en la posición indicada.

Nota: Para este tipo de funciones se debe siempre utilizar el operador <code>!</code>, esto se explica en la parte de funciones. En resumen, lo que hace es indicar que las funciones pueden realizar modificaciones a la estructura de datos.


In [14]:
arr = rand(1:10,10) 
#=La primera entrada indica el rango de valores a generar
y la segunda la cantidad de valores. =#

10-element Array{Int64,1}:
  7
 10
  2
  9
  9
  7
 10
  4
  1
  4

In [15]:
push!(arr,11)

11-element Array{Int64,1}:
  7
 10
  2
  9
  9
  7
 10
  4
  1
  4
 11

In [16]:
pop!(arr)

11

In [17]:
popat!(arr, 2)

10

In [18]:
insert!(arr, 2, 15)

10-element Array{Int64,1}:
  7
 15
  2
  9
  9
  7
 10
  4
  1
  4

## Control de Flujo

### While loop
Un loop de tipo _while_ es un pedazo de código el cual se repite infinitamente hasta que se ya no se cumpla una condición. En Julia para escribir un ciclo _while_ se utiliza la siguiente sintaxis: 
```julia
    while *condition*
    
        *codigo*
    
    end
```

In [19]:
condition = 0
while condition < 10
    condition +=1
    println("Numero de iteracion $condition")
end

Numero de iteracion 1
Numero de iteracion 2
Numero de iteracion 3
Numero de iteracion 4
Numero de iteracion 5
Numero de iteracion 6
Numero de iteracion 7
Numero de iteracion 8
Numero de iteracion 9
Numero de iteracion 10


Los _while_ siempre se terminan con keyword <code>end</code>. 

### For loop
Similar a un código _while_ este tipo de loop se repite siempre y cuando se cumple una condición. La diferencia nace de que se puede controlar cuantas veces realizar el loop. La sintaxis en Julia para un __for loop__ es:
```julia
    for *variable* in *rango o objeto*
        * codigo *
    end 
```

In [20]:
# Para crear un rango de valores se puede utilizar la nomenclatura 1:10 por ejemplo:
for i in 1:10 
    println("Numero de iteracion $i")
end 

Numero de iteracion 1
Numero de iteracion 2
Numero de iteracion 3
Numero de iteracion 4
Numero de iteracion 5
Numero de iteracion 6
Numero de iteracion 7
Numero de iteracion 8
Numero de iteracion 9
Numero de iteracion 10


In [21]:
# Tambien se puede iterar sobre ciertas estructuras de datos por ejemplo arreglos:
arr = rand(1:20, 10)
for i in arr
    println("Contenido del array $i")
end

Contenido del array 1
Contenido del array 14
Contenido del array 18
Contenido del array 7
Contenido del array 12
Contenido del array 12
Contenido del array 9
Contenido del array 11
Contenido del array 15
Contenido del array 17


In [22]:
dict = Dict("Max"=>1, "Min" => 10, "Med" => 5)
for i in dict
    println(i)
end

"Min" => 10
"Med" => 5
"Max" => 1


Para recorrer matrices en general se utilizan dos <code>for</code> loops de la siguiente forma:

In [23]:
matrix = zeros(3,3) #zeros(m,n) crea una matriz de tamaño mxn llena de 0s
for i in 1:3
    for j in 1:3
        matrix[i, j] = i + j
    end
end
matrix

3×3 Array{Float64,2}:
 2.0  3.0  4.0
 3.0  4.0  5.0
 4.0  5.0  6.0

Sin embargo, Julia tambien permite la siguiente sintaxis:

In [24]:
for i in 1:3, j in 1:3
    matrix[i, j] = i+j
end
matrix

3×3 Array{Float64,2}:
 2.0  3.0  4.0
 3.0  4.0  5.0
 4.0  5.0  6.0

Por ultimo, Julia permite algo muy similar a lo que se llama en Python como __List Comprehensions__, en Julia se llaman __Array Comprehensions__. Su sintaxis es la siguiente:

In [25]:
arr = [x^y for x in 1:5, y in 1:2]

5×2 Array{Int64,2}:
 1   1
 2   4
 3   9
 4  16
 5  25

In [26]:
arr = [w^2 for w in 1:10]

10-element Array{Int64,1}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

### Condicionales 
Los condicionales <code>if</code> y <code>else</code> sirven para ejecutar diferentes partes del código a partir de una condición, la sintaxis es:
```julia
    if *condition*
        *hacer algo*
    else 
        *hacer otra cosa*
    end
```
    Tambien se soporta la siguiente sintaxis: 
```julia
    if *condition*
        *hacer algo*
    elseif *condition 2*
        *hacer otra cosa*
    end
```
Por ejemplo entonces:

In [27]:
num1 = rand(1:10)
num2 = rand(1:10)
if num1>num2
    println("El numero 1 es mayor con valor de $num1")
else
    println("El numero 2 es mayor con valor de $num2")
end

El numero 2 es mayor con valor de 1


In [28]:
num3 = rand(1:10)
if num1>num2
    println("El numero 1 es mayor con valor de $num1")
elseif num3>num2
    println("El numero 3 es mayor con valor de $num3")
else
    println("El numero 2 es mayor con valor de $num2")
end

El numero 3 es mayor con valor de 6


Para este tipo de condiciones simples donde solo hay dos caminos como en el primer ejemplo existe otra sintaxis más corta la cual se puede utilizar por medio del operador <code>?</code>. Por ejemplo, si se desea retornar el número más grande:

In [29]:
num1 = rand(1:10)
num2 = rand(1:10)
(num1 > num2) ? num1 : num2 #Si la condicion se cumple se retorna num1 por ser mayor, caso contrario se retorna num2

8

Otra posibilidad en Julia es utilizar el operador <code>\&\&</code> de la siguiente forma:
```julia
    condition && b
```
Lo anterior significa que solo si la condición <code>condition</code> se cumple, en otras palabras es verdadera se realiza <code>b</code>.


In [30]:
num1 = rand(1:10)
num2 = rand(1:10)
(num1 > num2) && println("Num1 es mas grande")
(num2 > num1) && println("Num2 es mas grande");

Num1 es mas grande


## Funciones

#### Como declarar una función
En Julia las funciones se pueden declarar de varias maneras. La manera más general es la siguiente:


In [31]:
function elevar(x,y)
    x^y
end     

elevar (generic function with 1 method)

In [32]:
function f(x,y)
    x/2+y/2
end

f (generic function with 1 method)

Cuando se hace una función la última línea de código es lo que se retorna de la función por tanto no siempre es necesario utilizar el keyword <code>return</code>. Para llamar a una función se utiliza la siguiente sintaxis:

In [33]:
elevar(2,3)

8

In [34]:
f(10,20)

15.0

Las funciones anteriores solo hacen una cosa, funciones de este tipo muy sencillas se pueden declarar en una sola línea de código de la siguiente forma:

In [35]:
elevar2(x,y) = x^y

elevar2 (generic function with 1 method)

In [36]:
f2(x,y) = x/2 + y/2

f2 (generic function with 1 method)

In [37]:
elevar2(2,3)

8

In [38]:
f2(10,20)

15.0

El ultimo método a mencionar de crear funciones es por medio de funciones __Anónimas__.

In [39]:
elevar3 = (x,y) -> x^y

#5 (generic function with 1 method)

In [40]:
f3 = (x,y) -> x/2 + y/2

#7 (generic function with 1 method)

Estas funciones no requieren de un nombre como tal, sin embargo, si se les asigna un nombre por medio de un variable se pueden llamar de la misma forma que los ejemplos anteriores.

In [41]:
elevar3(2,3)

8

In [42]:
f3(10,20)

15.0

### Return en Julia
En Julia como se mencionó antes por defecto se retorna el ultimo valor de una función, sin embargo, si fuera una función más completa surge la necesidad de especificar que dato en particular retornar, para ello se utiliza el keyword <code>return</code>.

Si uno desea especificar un tipo de variable en específico a retornar, por ejemplo un <code>String</code> o <code>Int8</code> se hace con la siguientes nomenclatura:


In [43]:
function sum(a,b)::Int8
    return a+b
end
typeof(sum(2,4))

Int8

Como detalle final del uso de <code>return</code>, en Julia se pueden retornar varios valores de una función de forma fácil. Cuando se retornan varios valores lo que en realidad hace Julia es retornar un <code>Tuple</code> con los valores retornados. Esto se hace de la siguiente forma como ejemplo:

In [44]:
function num_calc(x,y)
    return x+y, x-y, x*y, x/y
end
num_calc(3,3)

(6, 0, 9, 1.0)

Para accesar los varios resultados se puede hacer:

In [45]:
suma, resta, mult, div = num_calc(3,3)
println(suma)
println(resta)
println(mult)
println(div)

6
0
9
1.0


### Significado del operador <code>!</code> en funciones
En Julia muchas de las funciones incluidas con el lenguaje tienen dos versiones, por ejemplo la función <code>sort()</code>. Las segunda versión se llama <code>sort!()</code>, el operador <code>!</code> lo que significa es que dicha función __si__ modifica los contenidos de su argumento. La diferencia se muestra mejor con un ejemplo:

In [46]:
arr = rand(1:10,5)

5-element Array{Int64,1}:
  4
  3
  1
 10
  9

In [47]:
println("Version sorted ", sort(arr))
println("Arr ", arr)

Version sorted [1, 3, 4, 9, 10]
Arr [4, 3, 1, 10, 9]


In [48]:
sort!(arr)
println("Arr despues de sort! ", arr)

Arr despues de sort! [1, 3, 4, 9, 10]


Nótese que solo cuando se utiliza <code>sort!()</code> el arreglo de entrada original __si__ es modificado.

### Uso del operador <code>.</code>
El operador de <code>.</code> en Julia funciona similar a como funciona en Matlab. Su función es que cuando se tiene un arreglo y se llama una función sobre este con el operador <code>.</code> la función se corre sobre cada uno de sus elementos. Este concepto se conoce como __Broadcasting__ en Julia. Por ejemplo, digamos que se desea elevar al cuadrado el valor de todos los elementos de un arreglo:

In [49]:
f(x) = x^2
arr = rand(1:10, 10)
f.(arr)

10-element Array{Int64,1}:
 100
  16
   1
  64
  49
  64
  16
   4
  81
 100

Otro ejemplo mas complicado puede ser, teniendo una matriz <code>A</code> quiero obtener una matriz <code>B</code> la cual se obtiene luego de pasar cada elemento de <code>A</code> por alguna clase de función:

In [50]:
A = rand(1:10, (3,3)) # Es sintaxis construye una matriz 3x3 con valores random entre 1-10

3×3 Array{Int64,2}:
 7  1  8
 4  3  2
 5  7  4

In [51]:
matrix_func(x) = x^3/3 -2x + x
B = matrix_func.(A)

3×3 Array{Float64,2}:
 107.333    -0.666667  162.667
  17.3333    6.0         0.666667
  36.6667  107.333      17.3333

Como ejemplo final, se muestra cómo obtener el cuadrado de una matriz en Julia:

In [52]:
f(x) = x^2
A = rand(1:10, (3,3))
f(A)

3×3 Array{Int64,2}:
 116   91  60
 124   97  63
 116  111  82